theme: jekyll-theme-cayman
title: MicroStrategy Embedding SDK Samples

exclude:
  - "page_navigation/src"
  - "page_navigation/build"
  - "page_navigation/node_modules"
  - "page_navigation/public"
  - "page_navigation/.vscode"
